export const categories = [
  {
    name: 'smileys',
    label: 'Smileys',
    icon: '😊',
    emojis: [
      '😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '😊', '😇',
      '🙂', '🙃', '😉', '😌', '😍', '🥰', '😘', '😗', '😙', '😚',
      '😋', '😛', '😝', '😜', '🤪', '🤨', '🧐', '🤓', '😎', '🤩',
      '🥳', '😏', '😒', '😞', '😔', '😟', '😕', '🙁', '☹️', '😣',
      '😖', '😫', '😩', '🥺', '😢', '😭', '😤', '😠', '😡', '🤬',
      '🤯', '😳', '🥵', '🥶', '😱', '😨', '😰', '😥', '😓', '🤗',
      '🤔', '🤭', '🤫', '🤥', '😶', '😐', '😑', '😬', '🙄', '😯',
      '😦', '😧', '😮', '😲', '🥱', '😴', '🤤', '😪', '😵', '🤐'
    ]
  },
  {
    name: 'gestures',
    label: 'Body',
    icon: '👍',
    emojis: [
      '👍', '👎', '👌', '✌️', '🤞', '🤟', '🤘', '🤙', '👈', '👉',
      '👆', '🖕', '👇', '☝️', '👋', '🤚', '🖐️', '✋', '🖖', '👏',
      '🙌', '👐', '🤲', '🤝', '🙏', '✍️', '💅', '🤳', '💪', '🦾',
      '🦵', '🦿', '🦶', '👂', '🦻', '👃', '🧠', '🫀', '🫁', '🦷',
      '🦴', '👀', '👁️', '👅', '👄', '💋', '🩸'
    ]
  },
  {
    name: 'animals',
    label: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯',
      '🦁', '🐮', '🐷', '🐽', '🐸', '🐵', '🙈', '🙉', '🙊', '🐒',
      '🐔', '🐧', '🐦', '🐤', '🐣', '🐥', '🦆', '🦅', '🦉', '🦇',
      '🐺', '🐗', '🐴', '🦄', '🐝', '🐛', '🦋', '🐌', '🐞', '🐜',
      '🦟', '🦗', '🕷️', '🕸️', '🦂', '🐢', '🐍', '🦎', '🦖', '🦕',
      '🐙', '🦑', '🦐', '🦞', '🦀', '🐡', '🐠', '🐟', '🐬', '🐳',
      '🐋', '🦈', '🐊', '🐅', '🐆', '🦓', '🦍', '🦧', '🐘', '🦛',
      '🦏', '🐪', '🐫', '🦒', '🦘', '🐃', '🐂', '🐄', '🐎', '🐖'
    ]
  },
  {
    name: 'food',
    label: 'Food & Drink',
    icon: '🍕',
    emojis: [
      '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐', '🍈',
      '🍒', '🍑', '🥭', '🍍', '🥥', '🥝', '🍅', '🍆', '🥑', '🥦',
      '🥬', '🥒', '🌶️', '🫑', '🌽', '🥕', '🫒', '🧄', '🧅', '🥔',
      '🍠', '🥐', '🥯', '🍞', '🥖', '🥨', '🧀', '🥚', '🍳', '🧈',
      '🥞', '🧇', '🥓', '🥩', '🍗', '🍖',, '🌭',
      '🍔', '🍟', '🍕', '🫓', '🥪', '🥙', '🧆', '🌮', '🌯', '🫔',
      '🥗', '🥘', '🫕', '🍝', '🍜', '🍲', '🍛', '🍣', '🍱', '🥟',
      '🦪', '🍤', '🍙', '🍚', '🍘', '🍥', '🥠', '🥮', '🍢', '🍡',
      '🍧', '🍨'
    ]
  },
  {
    name: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      '⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱',
      '🪀', '🏓', '🏸', '🏒', '🏑', '🥍', '🏏', '🪃', '🥅', '⛳',
      '🪁', '🏹', '🎣', '🤿', '🥊', '🥋', '🎽', '🛹', '🛷', '⛸️',
      '🥌', '🎿', '⛷️', '🏂', '🪂', '🏋️', '🤼', '🤸', '⛹️', '🤺',
      '🏇', '🧘', '🏄', '🏊', '🤽', '🚣', '🧗', '🚵', '🚴',
      '🏆', '🥇', '🥈', '🥉', '🏅', '🎖️', '🏵️', '🎗️', '🎫',
      '🎟️', '🎪', '🤹', '🎭', '🩰', '🎨', '🎬', '🎤', '🎧', '🎼',
      '🎵', '🎶'
    ]
  },
  {
    name: 'objects',
    label: 'Objects',
    icon: '🎁',
    emojis: [
      '🎁', '🎀', '🎊', '🎉', '🎈', '🎂', '🍰', '🧁', '🍭', '🍬',
      '🍫', '🍩', '🍪', '🎄', '🎃', '🎆', '🎇', '🧨', '✨',
      '📱', '💻', '🖥️', '🖨️', '⌨️', '🖱️', '🖲️', '💽', '💾', '💿',
      '📀', '🧮', '🎥', '🎞️', '📽️', '🎬', '📺', '📻', '🎙️', '🎚️',
      '🎛️', '🧭', '⏱️', '⏲️', '⏰', '🕰️', '⌛', '⏳', '📡', '🔋'
    ]
  }
];

export const emojiNames = {
  // Smileys
  '😀': 'grinning face',
  '😃': 'grinning face with big eyes',
  '😄': 'grinning face with smiling eyes',
  '😁': 'beaming face with smiling eyes',
  '😆': 'grinning squinting face',
  '😅': 'grinning face with sweat',
  '😂': 'face with tears of joy',
  '🤣': 'rolling on the floor laughing',
  '😊': 'smiling face with smiling eyes',
  '😇': 'smiling face with halo',
  '🙂': 'slightly smiling face',
  '🙃': 'upside-down face',
  '😉': 'winking face',
  '😌': 'relieved face',
  '😍': 'smiling face with heart-eyes',
  '🥰': 'smiling face with hearts',
  '😘': 'face blowing a kiss',
  '😗': 'kissing face',
  '😙': 'kissing face with smiling eyes',
  '😚': 'kissing face with closed eyes',
  '😋': 'face savoring food',
  '😛': 'face with tongue',
  '😝': 'squinting face with tongue',
  '😜': 'winking face with tongue',
  '🤪': 'zany face',
  '🤨': 'face with raised eyebrow',
  '🧐': 'face with monocle',
  '🤓': 'nerd face',
  '😎': 'smiling face with sunglasses',
  '🤩': 'star-struck',
  '🥳': 'partying face',
  '😏': 'smirking face',
  '😒': 'unamused face',
  '😞': 'disappointed face',
  '😔': 'pensive face',
  '😟': 'worried face',
  '😕': 'confused face',
  '🙁': 'slightly frowning face',
  '☹️': 'frowning face',
  '😣': 'persevering face',
  '😖': 'confounded face',
  '😫': 'tired face',
  '😩': 'weary face',
  '🥺': 'pleading face',
  '😢': 'crying face',
  '😭': 'loudly crying face',
  '😤': 'face with steam from nose',
  '😠': 'angry face',
  '😡': 'pouting face',
  '🤬': 'face with symbols on mouth',
  '🤯': 'exploding head',
  '😳': 'flushed face',
  '🥵': 'hot face',
  '🥶': 'cold face',
  '😱': 'face screaming in fear',
  '😨': 'fearful face',
  '😰': 'anxious face with sweat',
  '😥': 'sad but relieved face',
  '😓': 'downcast face with sweat',
  '🤗': 'hugging face',
  '🤔': 'thinking face',
  '🤭': 'face with hand over mouth',
  '🤫': 'shushing face',
  '🤥': 'lying face',
  '😶': 'face without mouth',
  '😐': 'neutral face',
  '😑': 'expressionless face',
  '😬': 'grimacing face',
  '🙄': 'face with rolling eyes',
  '😯': 'hushed face',
  '😦': 'frowning face with open mouth',
  '😧': 'anguished face',
  '😮': 'face with open mouth',
  '😲': 'astonished face',
  '🥱': 'yawning face',
  '😴': 'sleeping face',
  '🤤': 'drooling face',
  '😪': 'sleepy face',
  '😵': 'dizzy face',
  '🤐': 'zipper-mouth face',

  // Gestures & Body
  '👍': 'thumbs up',
  '👎': 'thumbs down',
  '👌': 'OK hand',
  '✌️': 'victory hand',
  '🤞': 'crossed fingers',
  '🤟': 'love-you gesture',
  '🤘': 'sign of the horns',
  '🤙': 'call me hand',
  '👈': 'backhand index pointing left',
  '👉': 'backhand index pointing right',
  '👆': 'backhand index pointing up',
  '🖕': 'middle finger',
  '👇': 'backhand index pointing down',
  '☝️': 'index pointing up',
  '👋': 'waving hand',
  '🤚': 'raised back of hand',
  '🖐️': 'hand with fingers splayed',
  '✋': 'raised hand',
  '🖖': 'vulcan salute',
  '👏': 'clapping hands',
  '🙌': 'raising hands',
  '👐': 'open hands',
  '🤲': 'palms up together',
  '🤝': 'handshake',
  '🙏': 'folded hands',
  '✍️': 'writing hand',
  '💅': 'nail polish',
  '🤳': 'selfie',
  '💪': 'flexed biceps',
  '🦾': 'mechanical arm',
  '🦵': 'leg',
  '🦿': 'mechanical leg',
  '🦶': 'foot',
  '👂': 'ear',
  '🦻': 'ear with hearing aid',
  '👃': 'nose',
  '🧠': 'brain',
  '🫀': 'anatomical heart',
  '🫁': 'lungs',
  '🦷': 'tooth',
  '🦴': 'bone',
  '👀': 'eyes',
  '👁️': 'eye',
  '👅': 'tongue',
  '👄': 'mouth',
  '💋': 'kiss mark',
  '🩸': 'drop of blood',

  // Animals & Nature
  '🐶': 'dog face',
  '🐱': 'cat face',
  '🐭': 'mouse face',
  '🐹': 'hamster face',
  '🐰': 'rabbit face',
  '🦊': 'fox face',
  '🐻': 'bear face',
  '🐼': 'panda face',
  '🐨': 'koala',
  '🐯': 'tiger face',
  '🦁': 'lion face',
  '🐮': 'cow face',
  '🐷': 'pig face',
  '🐽': 'pig nose',
  '🐸': 'frog face',
  '🐵': 'monkey face',
  '🙈': 'see-no-evil monkey',
  '🙉': 'hear-no-evil monkey',
  '🙊': 'speak-no-evil monkey',
  '🐒': 'monkey',
  '🐔': 'chicken',
  '🐧': 'penguin',
  '🐦': 'bird',
  '🐤': 'baby chick',
  '🐣': 'hatching chick',
  '🐥': 'front-facing baby chick',
  '🦆': 'duck',
  '🦅': 'eagle',
  '🦉': 'owl',
  '🦇': 'bat',
  '🐺': 'wolf face',
  '🐗': 'boar',
  '🐴': 'horse face',
  '🦄': 'unicorn face',
  '🐝': 'honeybee',
  '🐛': 'bug',
  '🦋': 'butterfly',
  '🐌': 'snail',
  '🐞': 'lady beetle',
  '🐜': 'ant',
  '🦟': 'mosquito',
  '🦗': 'cricket',
  '🕷️': 'spider',
  '🕸️': 'spider web',
  '🦂': 'scorpion',
  '🐢': 'turtle',
  '🐍': 'snake',
  '🦎': 'lizard',
  '🦖': 'T-rex',
  '🦕': 'sauropod',
  '🐙': 'octopus',
  '🦑': 'squid',
  '🦐': 'shrimp',
  '🦞': 'lobster',
  '🦀': 'crab',
  '🐡': 'blowfish',
  '🐠': 'tropical fish',
  '🐟': 'fish',
  '🐬': 'dolphin',
  '🐳': 'spouting whale',
  '🐋': 'whale',
  '🦈': 'shark',
  '🐊': 'crocodile',
  '🐅': 'tiger',
  '🐆': 'leopard',
  '🦓': 'zebra',
  '🦍': 'gorilla',
  '🦧': 'orangutan',
  '🐘': 'elephant',
  '🦛': 'hippopotamus',
  '🦏': 'rhinoceros',
  '🐪': 'dromedary camel',
  '🐫': 'two-hump camel',
  '🦒': 'giraffe',
  '🦘': 'kangaroo',
  '🐃': 'water buffalo',
  '🐂': 'ox',
  '🐄': 'cow',
  '🐎': 'horse',
  '🐖': 'pig',

  // Food & Drink
  '🍎': 'red apple',
  '🍐': 'pear',
  '🍊': 'tangerine',
  '🍋': 'lemon',
  '🍌': 'banana',
  '🍉': 'watermelon',
  '🍇': 'grapes',
  '🍓': 'strawberry',
  '🫐': 'blueberries',
  '🍈': 'melon',
  '🍒': 'cherries',
  '🍑': 'peach',
  '🥭': 'mango',
  '🍍': 'pineapple',
  '🥥': 'coconut',
  '🥝': 'kiwi fruit',
  '🍅': 'tomato',
  '🍆': 'eggplant',
  '🥑': 'avocado',
  '🥦': 'broccoli',
  '🥬': 'leafy green',
  '🥒': 'cucumber',
  '🌶️': 'hot pepper',
  '🫑': 'bell pepper',
  '🌽': 'ear of corn',
  '🥕': 'carrot',
  '🫒': 'olive',
  '🧄': 'garlic',
  '🧅': 'onion',
  '🥔': 'potato',
  '🍠': 'roasted sweet potato',
  '🥐': 'croissant',
  '🥯': 'bagel',
  '🍞': 'bread',
  '🥖': 'baguette bread',
  '🥨': 'pretzel',
  '🧀': 'cheese wedge',
  '🥚': 'egg',
  '🍳': 'cooking',
  '🧈': 'butter',
  '🥞': 'pancakes',
  '🧇': 'waffle',
  '🥓': 'bacon',
  '🥩': 'cut of meat',
  '🍗': 'poultry leg',
  '🍖': 'meat on bone',
  '🌭': 'hot dog',
  '🍔': 'hamburger',
  '🍟': 'french fries',
  '🍕': 'pizza',
  '🫓': 'flatbread',
  '🥪': 'sandwich',
  '🥙': 'stuffed flatbread',
  '🧆': 'falafel',
  '🌮': 'taco',
  '🌯': 'burrito',
  '🫔': 'tamale',
  '🥗': 'green salad',
  '🥘': 'shallow pan of food',
  '🫕': 'fondue',
  '🍝': 'spaghetti',
  '🍜': 'steaming bowl',
  '🍲': 'pot of food',
  '🍛': 'curry rice',
  '🍣': 'sushi',
  '🍱': 'bento box',
  '🥟': 'dumpling',
  '🦪': 'oyster',
  '🍤': 'fried shrimp',
  '🍙': 'rice ball',
  '🍚': 'cooked rice',
  '🍘': 'rice cracker',
  '🍥': 'fish cake with swirl',
  '🥠': 'fortune cookie',
  '🥮': 'moon cake',
  '🍢': 'oden',
  '🍡': 'dango',
  '🍧': 'shaved ice',
  '🍨': 'ice cream',

  // Activities
  '⚽': 'soccer ball',
  '🏀': 'basketball',
  '🏈': 'american football',
  '⚾': 'baseball',
  '🥎': 'softball',
  '🎾': 'tennis',
  '🏐': 'volleyball',
  '🏉': 'rugby football',
  '🥏': 'flying disc',
  '🎱': 'pool 8 ball',
  '🪀': 'yo-yo',
  '🏓': 'ping pong',
  '🏸': 'badminton',
  '🏒': 'ice hockey',
  '🏑': 'field hockey',
  '🥍': 'lacrosse',
  '🏏': 'cricket game',
  '🪃': 'boomerang',
  '🥅': 'goal net',
  '⛳': 'flag in hole',
  '🪁': 'kite',
  '🏹': 'archery',
  '🎣': 'fishing pole',
  '🤿': 'diving mask',
  '🥊': 'boxing glove',
  '🥋': 'martial arts uniform',
  '🎽': 'running shirt',
  '🛹': 'skateboard',
  '🛷': 'sled',
  '⛸️': 'ice skate',
  '🥌': 'curling stone',
  '🎿': 'skis',
  '⛷️': 'skier',
  '🏂': 'snowboarder',
  '🪂': 'parachute',
  '🏋️': 'weight lifter',
  '🤼': 'people wrestling',
  '🤸': 'person cartwheeling',
  '⛹️': 'person bouncing ball',
  '🤺': 'person fencing',
  '🏇': 'horse racing',
  '🧘': 'person in lotus position',
  '🏄': 'person surfing',
  '🏊': 'person swimming',
  '🤽': 'person playing water polo',
  '🚣': 'person rowing boat',
  '🧗': 'person climbing',
  '🚵': 'person mountain biking',
  '🚴': 'person biking',
  '🏆': 'trophy',
  '🥇': '1st place medal',
  '🥈': '2nd place medal',
  '🥉': '3rd place medal',
  '🏅': 'sports medal',
  '🎖️': 'military medal',
  '🏵️': 'rosette',
  '🎗️': 'reminder ribbon',
  '🎫': 'ticket',
  '🎟️': 'admission tickets',
  '🎪': 'circus tent',
  '🤹': 'person juggling',
  '🎭': 'performing arts',
  '🩰': 'ballet shoes',
  '🎨': 'artist palette',
  '🎬': 'clapper board',
  '🎤': 'microphone',
  '🎧': 'headphone',
  '🎼': 'musical score',
  '🎵': 'musical note',
  '🎶': 'musical notes',

  // Objects
  '🎁': 'wrapped gift',
  '🎀': 'ribbon',
  '🎊': 'confetti ball',
  '🎉': 'party popper',
  '🎈': 'balloon',
  '🎂': 'birthday cake',
  '🍰': 'shortcake',
  '🧁': 'cupcake',
  '🍭': 'lollipop',
  '🍬': 'candy',
  '🍫': 'chocolate bar',
  '🍩': 'doughnut',
  '🍪': 'cookie',
  '🎄': 'christmas tree',
  '🎃': 'jack-o-lantern',
  '🎆': 'fireworks',
  '🎇': 'sparkler',
  '🧨': 'firecracker',
  '✨': 'sparkles',
  '📱': 'mobile phone',
  '💻': 'laptop computer',
  '🖥️': 'desktop computer',
  '🖨️': 'printer',
  '⌨️': 'keyboard',
  '🖱️': 'computer mouse',
  '🖲️': 'trackball',
  '💽': 'computer disk',
  '💾': 'floppy disk',
  '💿': 'optical disk',
  '📀': 'dvd',
  '🧮': 'abacus',
  '🎥': 'movie camera',
  '🎞️': 'film frames',
  '📽️': 'film projector',
  '📺': 'television',
  '📻': 'radio',
  '🎙️': 'studio microphone',
  '🎚️': 'level slider',
  '🎛️': 'control knobs',
  '🧭': 'compass',
  '⏱️': 'stopwatch',
  '⏲️': 'timer clock',
  '⏰': 'alarm clock',
  '🕰️': 'mantelpiece clock',
  '⌛': 'hourglass done',
  '⏳': 'hourglass not done',
  '📡': 'satellite antenna',
  '🔋': 'battery'
};
