# Use latest Node LTS to build
FROM node:lts AS builder
# Copy Vue.js code
WORKDIR /app
COPY ./webui .
# Build Vue.js into plain HTML/CSS/JS
RUN yarn install
RUN yarn build-prod

### Create final container
FROM nginx:stable
### Copy the (built) app from the builder image
COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/assets /usr/share/nginx/html/assets