FROM golang:1.23.9 AS builder
WORKDIR /src/
COPY . .
RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bookworm
EXPOSE 3000
WORKDIR /app/
COPY --from=builder /app/webapi ./
COPY --from=builder /src/service/database/initdb.sql ./service/database/initdb.sql
CMD ["/app/webapi"]
