FROM node:lts AS builder
WORKDIR /app
COPY ./webui .
RUN yarn install
RUN yarn build-prod

FROM nginx:stable
COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/assets /usr/share/nginx/html/assets
